{{- if and .Values.carto.apiKey.value (not .Values.carto.apiKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.cartoApiKeySecretName" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.carto.apiKey.secretKey }}: {{ .Values.carto.apiKey.value | quote }}
{{- end }}
