name: Google Cloud Run Deploy
# https://github.com/google-github-actions/setup-gcloud
on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCR_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: travel-proton-name

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
            service_account_key: ${{ secrets.GCR_SA_KEY }}
            project_id: ${{ secrets.GCR_PROJECT }}

      # Build and push image to Google Container Registry
      - name: Build
        run: |-
          docker build \
            --tag "gcr.io/${{github.repository}}/$IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            
      - name: Publish
        run: |-
          docker push "gcr.io/${{github.repository}}/$IMAGE:$GITHUB_SHA"

      # Deploy image to Cloud Run
      - name: Deploy GCR
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "gcr.io/${{github.repository}}/$IMAGE:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
