name: Google Cloud Run Deploy
# https://github.com/google-github-actions/setup-gcloud
on:
  push:
    branches:
      - master

env:
  GCR_PROJECT_ID: ${{ secrets.GCR_PROJECT_ID }}
  RUN_REGION: us-central1
  SERVICE_NAME: travel-proton-name

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
            service_account_key: ${{ secrets.GCR_SA_KEY }}
            project_id: ${{ secrets.GCR_PROJECT_ID }}

      #- name: Build
        #run: |-
          #docker build \
            #--tag "gcr.io/$GCR_PROJECT_ID/${{github.repository}}/$GITHUB_SHA" \
            #--build-arg GITHUB_SHA="$GITHUB_SHA" \
            #--build-arg GITHUB_REF="$GITHUB_REF" \
            # .

      - name: Build
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$GCR_PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
            
      #- name: Publish
        #run: |-
          #docker push "gcr.io/$GCR_PROJECT_ID/${{github.repository}}/$GITHUB_SHA"

      # Deploy image to Cloud Run
      - name: Deploy
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --image "gcr.io/$GCR_PROJECT_ID/${{github.repository}}/$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
